"""create initial tables

Revision ID: c5a1f06963d7
Revises: 
Create Date: 2026-02-05 22:55:56.336465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a1f06963d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=8), nullable=True),
    sa.Column('minor_units', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=True)
    op.create_table('fiscal_years',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('base_currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_fiscal_years_base_currency_id'), 'fiscal_years', ['base_currency_id'], unique=False)
    op.create_index(op.f('ix_fiscal_years_name'), 'fiscal_years', ['name'], unique=False)
    op.create_index(op.f('ix_fiscal_years_uuid'), 'fiscal_years', ['uuid'], unique=False)
    op.create_table('ledger_accounts',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'INCOME', 'EXPENSE', 'EQUITY', name='ledgeraccounttype'), nullable=False),
    sa.Column('opened_on', sa.Date(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_ledger_accounts_code'), 'ledger_accounts', ['code'], unique=False)
    op.create_index(op.f('ix_ledger_accounts_currency_id'), 'ledger_accounts', ['currency_id'], unique=False)
    op.create_index(op.f('ix_ledger_accounts_name'), 'ledger_accounts', ['name'], unique=False)
    op.create_index(op.f('ix_ledger_accounts_type'), 'ledger_accounts', ['type'], unique=False)
    op.create_index(op.f('ix_ledger_accounts_uuid'), 'ledger_accounts', ['uuid'], unique=False)
    op.create_table('ledger_account_budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ledger_account_id', sa.String(length=36), nullable=False),
    sa.Column('fiscal_year_id', sa.String(length=36), nullable=False),
    sa.Column('budget_monthly', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('budget_yearly', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['ledger_accounts.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ledger_account_id', 'fiscal_year_id', name='uq_budget_account_year')
    )
    op.create_index('ix_budget_account_year', 'ledger_account_budgets', ['ledger_account_id', 'fiscal_year_id'], unique=False)
    op.create_index(op.f('ix_ledger_account_budgets_fiscal_year_id'), 'ledger_account_budgets', ['fiscal_year_id'], unique=False)
    op.create_index(op.f('ix_ledger_account_budgets_ledger_account_id'), 'ledger_account_budgets', ['ledger_account_id'], unique=False)
    op.create_table('transactions',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('receipt_no', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payee', sa.String(length=128), nullable=True),
    sa.Column('import_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('fiscal_year_id', sa.String(length=36), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.uuid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_transactions_booking_date'), 'transactions', ['booking_date'], unique=False)
    op.create_index(op.f('ix_transactions_currency_id'), 'transactions', ['currency_id'], unique=False)
    op.create_index(op.f('ix_transactions_fiscal_year_id'), 'transactions', ['fiscal_year_id'], unique=False)
    op.create_index(op.f('ix_transactions_import_id'), 'transactions', ['import_id'], unique=True)
    op.create_index(op.f('ix_transactions_payee'), 'transactions', ['payee'], unique=False)
    op.create_index(op.f('ix_transactions_receipt_no'), 'transactions', ['receipt_no'], unique=False)
    op.create_index(op.f('ix_transactions_uuid'), 'transactions', ['uuid'], unique=False)
    op.create_index('ix_transactions_year_date', 'transactions', ['fiscal_year_id', 'booking_date'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_uuid', sa.String(length=36), nullable=False),
    sa.Column('ledger_account_uuid', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_account_uuid'], ['ledger_accounts.uuid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_uuid'], ['transactions.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_ledger_account_uuid'), 'entries', ['ledger_account_uuid'], unique=False)
    op.create_index(op.f('ix_entries_transaction_uuid'), 'entries', ['transaction_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_transaction_uuid'), table_name='entries')
    op.drop_index(op.f('ix_entries_ledger_account_uuid'), table_name='entries')
    op.drop_table('entries')
    op.drop_index('ix_transactions_year_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_uuid'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_receipt_no'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payee'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_import_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_fiscal_year_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_currency_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_booking_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_ledger_account_budgets_ledger_account_id'), table_name='ledger_account_budgets')
    op.drop_index(op.f('ix_ledger_account_budgets_fiscal_year_id'), table_name='ledger_account_budgets')
    op.drop_index('ix_budget_account_year', table_name='ledger_account_budgets')
    op.drop_table('ledger_account_budgets')
    op.drop_index(op.f('ix_ledger_accounts_uuid'), table_name='ledger_accounts')
    op.drop_index(op.f('ix_ledger_accounts_type'), table_name='ledger_accounts')
    op.drop_index(op.f('ix_ledger_accounts_name'), table_name='ledger_accounts')
    op.drop_index(op.f('ix_ledger_accounts_currency_id'), table_name='ledger_accounts')
    op.drop_index(op.f('ix_ledger_accounts_code'), table_name='ledger_accounts')
    op.drop_table('ledger_accounts')
    op.drop_index(op.f('ix_fiscal_years_uuid'), table_name='fiscal_years')
    op.drop_index(op.f('ix_fiscal_years_name'), table_name='fiscal_years')
    op.drop_index(op.f('ix_fiscal_years_base_currency_id'), table_name='fiscal_years')
    op.drop_table('fiscal_years')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
